### ISSUE TITLE
Comments.config Drops an exception, and the custom templates are not working as well 

### ISSUE THREAD

**Issue by JefferyHus** [komentify/meteor-comments-ui#102]
when I try to set some configurations to the package as follow:
`// Comments config server side

Comments.config({
  replies: false,
  onEvent: (name, action, payload) => {
    // e.g send a mail
    console.log(name, action);
  }
});`
it drops an error which says that the comments object has no 'config' object or function.

one more thing is the custom templates, when I create templates on my view and then call `{{> commentsBox }}` by passing a custom teplate name to `textareaTemplate="myArea"` it does not use it and keeps loading the original design.

**Comment by matteodem** [comment]
cannot reproduce this, please give me a reproduction repository if this problem keeps persisting.
