### ISSUE TITLE
Breaking Match error [Meteor 1.4.2]

### ISSUE THREAD

**Issue by tmpg** [komentify/meteor-comments-ui#112]
> Exception from sub comments/reference id kzPCihAybNMFpbnzf Error: Match error: Expected number, got object
> at exports.check (packages/check.js:57:15)
> at Subscription.<anonymous> (packages/arkham:comments-ui/lib/server/publish.js:65:3)
> at Subscription.prepareOptions (packages/reywood_publish-composite.js:459:43)
> at Subscription._handler (packages/reywood_publish-composite.js:427:46)
> at packages/check.js:130:16
> at [object Object]._.extend.withValue (packages/meteor.js:1122:17)
> at Object.exports.Match._failIfArgumentsAreNotAllChecked (packages/check.js:129:41)
> at maybeAuditArgumentChecks (packages/ddp-server/livedata_server.js:1709:18)
> at Subscription._runHandler (packages/ddp-server/livedata_server.js:1027:17)
> at Session._startSubscription (packages/ddp-server/livedata_server.js:845:9)
> Sanitized and reported to the client as: Match failed [400]

When looking at line 65 (comments-ui/lib/server/publish.js) it seems to not like, **skip = 0**:

Meteor.publishComposite('comments/reference', function (id, sorting, limit,skip = 0) {
  check(id, String)
  check(sorting, String)
  check(limit, Number)
  **check(skip, Number)** //line 65

  return getCompositeCommentCursor(Comments._collection.find(
    { referenceId: id },
    { limit, skip, sort: Comments.getSortOption(sorting) }
  ))
})

Let me know what you would suggest.

Thanks

**Comment by matteodem** [comment]
When does that problem occur?

**Comment by matteodem** [comment]
Do you have a reproduction repository?
