### ISSUE TITLE
Materialize template

### ISSUE THREAD

**Issue by lb-** [komentify/meteor-comments-ui#18]
Happy to take a PR for a materialize template?
http://materializecss.com/forms.html

Or do you have one in the works?

**Comment by matteodem** [comment]
Sure stuff, I'd love to have one.

**Comment by joaobarcia** [comment]
+1 :)

**Comment by thomasandersen01** [comment]
+1

**Comment by matteodem** [comment]
I gave my feedback. Probably gonna merge it when I got time and do some adjustements.

**Comment by thomasandersen01** [comment]
Great @matteodem Looking forward to it.

**Comment by matteodem** [comment]
Closing this as the goal of this pkg won't be supporting loads of frameworks, but rather have a clean API that allows to easily rebuild the widget. see #119 and #114
