### ISSUE TITLE
Create a hook for admin validation

### ISSUE THREAD

**Issue by oohaysmlm** [komentify/meteor-comments-ui#76]
Perhaps create a new config setting that takes a function that is passed the UserID and the DocumentId  and can be used to validate whether or not a user has admin privileges to edit/remove the comment.  This way administrators could remove offensive content.  I will be working on this today in my own build, and am happy to submit a pull request if you are interested in incorporating the feature.

**Comment by oohaysmlm** [comment]
Added the functionality described above in [Pull Request #77](https://github.com/ARKHAM-Enterprises/meteor-comments-ui/pull/77)

**Comment by matteodem** [comment]
Awesome, will have a look at this next week!

**Comment by matteodem** [comment]
I'm closing this as there's basic comment moderation now available. Very thankful for the implementation you have provided though.
