### ISSUE TITLE
Upvote / Downvote Rating

### ISSUE THREAD

**Issue by mayvn10** [komentify/meteor-comments-ui#80]
@matteodem I'd like to request a feature where admin can use client side config to turn on an upvote/downvote system (so it's not on by default).

**Comment by matteodem** [comment]
Makes sense, will keep that on the radar. It's something that's also easily implementable in a PR

**Comment by matteodem** [comment]
Part of release `v1.2.0`, see https://github.com/komentify/meteor-comments-ui/blob/master/GUIDE.md#rating-comments
